"""Updated backup table

Revision ID: 3ec1b0ca9915
Revises: d045a85da6d7
Create Date: 2024-10-03 19:30:34.715147
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3ec1b0ca9915'
down_revision = 'd045a85da6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup', schema=None) as batch_op:
        # Adding a new column to the 'backup' table
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        # Creating a foreign key constraint with a specified name
        batch_op.create_foreign_key('fk_backup_owner', 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup', schema=None) as batch_op:
        # Dropping the foreign key constraint using its name
        batch_op.drop_constraint('fk_backup_owner', 'backup', type_='foreignkey')
        # Dropping the 'owner_id' column from the 'backup' table
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
